follower_limit: 10
user_limit: 10
admin_user_limit: 20
admin_category_limit: 9
admin_word_limit: 20
user_category_limit: 20
category_lesson_limit: 5
default_answer_limit: 2
correct_answers_min: 1
word_of_list_limit: 20
